[package]
name = "rfc2616"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
native-tls = "0.2.12"
rfc3986 = { version = "0.1.0", path = "../rfc3986.rs" }
